title: Dank Dude  
author: Batman
email: batman@wayne.com
description: > # this means to ignore newlines until "baseurl:"
  This is batman, I wear a suite to save the world for crazy people!

# social links
twitter_username: batman
github_username:  batman

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
